CREATE TABLE FUSION.USER (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.PROFILE (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  ALIAS VARCHAR(255),
  LASTNAME VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LAST_LOGIN TIMESTAMP NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  USER_ID VARCHAR(36) NOT NULL,
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.GROUP (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.EMAIL (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE FUSION.LANGUAGE (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  CODE VARCHAR(13) NOT NULL,
  LABEL VARCHAR(255) NOT NULL
);

CREATE TABLE FUSION.TEXT (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  LANGUAGE_ID VARCHAR(36) NOT NULL,
  CONTENT TEXT NOT NULL
);

CREATE TABLE FUSION.ORGANIZATIONTYPE (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  LABEL_TEXT_ID VARCHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.ORGANIZATION (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  ORGANIZATIONTYPE_ID VARCHAR(36) NOT NULL,
  QUERYABLE TINYINT(1) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.FILESYSTEM (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  ROOTDIR_ID VARCHAR(36) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  SHARED TINYINT(1) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.APPLICATION (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  APP_UNIVERSAL_ID VARCHAR(36) NOT NULL,
  VERSION VARCHAR(255) NOT NULL,
  STATUS TINYINT(1) NOT NULL,
  MANIFEST_URL VARCHAR(511) NOT NULL,
  STORE_URL VARCHAR(511) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.PERMISSION (
  _key VARCHAR(36) NOT NULL PRIMARY KEY,
  ID VARCHAR(36) NOT NULL,
  `KEY` VARCHAR(255) NOT NULL,
  LABEL_TEXT_ID VARCHAR(36) NOT NULL,
  DESCRIPTION_TEXT_ID VARCHAR(36) NOT NULL,
  EDITABLE TINYINT(1) NOT NULL,
  APPLICATION_ID VARCHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE FUSION.PROFILE_PERMISSION (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  PROFILE_ID VARCHAR(36) NOT NULL,
  PERMISSION_ID VARCHAR(36) NOT NULL
);

CREATE TABLE FUSION.GROUP_PERMISSION (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  GROUP_ID VARCHAR(36) NOT NULL,
  PERMISSION_ID VARCHAR(36) NOT NULL
);

CREATE TABLE FUSION.PROFILE_EMAIL (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  PROFILE_ID VARCHAR(36) NOT NULL,
  EMAIL_ID VARCHAR(36) NOT NULL,
  IS_MAIN TINYINT(1) NOT NULL
);

CREATE TABLE FUSION.FILESYSTEM_ORGANIZATION (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  FILESYSTEM_ID VARCHAR(36) NOT NULL,
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  IS_DEFAULT TINYINT(1) NOT NULL
);

CREATE TABLE FUSION.ORGANIZATION_APPLICATION (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  ORGANIZATION_ID VARCHAR(36) NOT NULL,
  APPLICATION_ID VARCHAR(36) NOT NULL,
  STATUS TINYINT(1) NOT NULL,
  LICENSE_FILE_FS_ID VARCHAR(36) NOT NULL,
  LICENSE_FILE_ID VARCHAR(36) NOT NULL
);

CREATE TABLE FUSION.PROFILE_GROUP (
  _key VARCHAR(73) NOT NULL PRIMARY KEY,
  PROFILE_ID VARCHAR(36) NOT NULL,
  GROUP_ID VARCHAR(36) NOT NULL
);

