SELECT perm.ID, perm.`KEY`, perm.EDITABLE, perm.LABEL_TEXT_ID, perm.DESCRIPTION_TEXT_ID, perm.CREATED_AT, perm.UPDATED_AT,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|>|', p.ID, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT),'') SEPARATOR '||'),'') as PROFILES,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|>|', g.ID, g.NAME, g.CREATED_AT, g.UPDATED_AT),'') SEPARATOR '||'),'') as `GROUPS`,
NULLIF(CONCAT_WS('||', a.ID, a.APP_UNIVERSAL_ID, a.`VERSION`, a.STATUS, a.MANIFEST_URL, a.STORE_URL, a.CREATED_AT, a.UPDATED_AT),'') as APPLICATION,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|>|', t.ID, l.ID, l.CODE, l.LABEL, t.CONTENT),'') SEPARATOR '||'),'') as LABEL,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|>|', td.ID, ld.ID, ld.CODE, ld.LABEL, td.CONTENT),'') SEPARATOR '||'),'') as DESCRIPTION
FROM (
	SELECT ID, `KEY`, EDITABLE, LABEL_TEXT_ID, DESCRIPTION_TEXT_ID, APPLICATION_ID, CREATED_AT, UPDATED_AT
	FROM $SCHEMA.PERMISSION $PAGINATION
) AS perm
LEFT JOIN $SCHEMA.PROFILE_PERMISSION pp ON pp.PERMISSION_ID = perm.ID
LEFT JOIN $SCHEMA.PROFILE W_p ON W_p.ID = pp.PROFILE_ID
LEFT JOIN $SCHEMA.PROFILE p ON p.ID = pp.PROFILE_ID
LEFT JOIN $SCHEMA.GROUP_PERMISSION gp ON gp.PERMISSION_ID = perm.ID
LEFT JOIN $SCHEMA.`GROUP` W_g ON W_g.ID = gp.GROUP_ID
LEFT JOIN $SCHEMA.`GROUP` g ON g.ID = gp.GROUP_ID
INNER JOIN $SCHEMA.APPLICATION W_a ON W_a.ID = perm.APPLICATION_ID
INNER JOIN $SCHEMA.APPLICATION a ON a.ID = perm.APPLICATION_ID
INNER JOIN $SCHEMA.`TEXT` W_t ON W_t.ID = perm.LABEL_TEXT_ID
INNER JOIN $SCHEMA.`TEXT` t ON t.ID = perm.LABEL_TEXT_ID
INNER JOIN $SCHEMA.`LANGUAGE` l ON l.ID = t.LANGUAGE_ID
INNER JOIN $SCHEMA.`TEXT` W_td ON W_td.ID = perm.DESCRIPTION_TEXT_ID
INNER JOIN $SCHEMA.`TEXT` td ON td.ID = perm.DESCRIPTION_TEXT_ID
INNER JOIN $SCHEMA.`LANGUAGE` ld ON ld.ID = td.LANGUAGE_ID
$WHERE_STATEMENT
GROUP BY perm.ID, perm.`KEY`, perm.EDITABLE, perm.LABEL_TEXT_ID, perm.DESCRIPTION_TEXT_ID, perm.CREATED_AT, perm.UPDATED_AT, APPLICATION
$ORDER_BY_STATEMENT;