SELECT p.ID, p.ALIAS, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT,
NULLIF(CONCAT_WS('||', u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT),'') as `USER`,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', e.ID, e.ADDRESS, pe.IS_MAIN),'') SEPARATOR '|^|'),'') as EMAILS,
NULLIF(CONCAT_WS('||', o.ID, o.LABEL, o.QUERYABLE, o.CREATED_AT, o.UPDATED_AT, o.ORGANIZATIONTYPE, o.ORG_TYPE_LABEL),'') as ORGANIZATION,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', g.ID, g.NAME, g.CREATED_AT, g.UPDATED_AT),'') SEPARATOR '|^|'),'') as `GROUPS`,
NULLIF(GROUP_CONCAT(
	DISTINCT NULLIF(CONCAT_WS('||', perm.ID, perm.`KEY`, perm.EDITABLE, perm.APPLICATION_ID, perm.CREATED_AT, perm.UPDATED_AT, perm.LABEL, perm.DESCRIPTION),'')
	SEPARATOR '|^'),''
) as `PERMISSIONS`
FROM (
	SELECT ID, ALIAS, LASTNAME, FIRSTNAME, LAST_LOGIN, IS_ACTIVE, USER_ID, CREATED_AT, UPDATED_AT, ORGANIZATION_ID
	FROM $SCHEMA.PROFILE $PAGINATION
) AS p
INNER JOIN $SCHEMA.`USER` W_u ON W_u.ID = p.USER_ID
INNER JOIN $SCHEMA.`USER` u ON u.ID = p.USER_ID
INNER JOIN $SCHEMA.PROFILE_EMAIL pe ON pe.PROFILE_ID = p.ID
INNER JOIN $SCHEMA.EMAIL W_e ON W_e.ID = pe.EMAIL_ID
INNER JOIN $SCHEMA.EMAIL e ON e.ID = pe.EMAIL_ID
INNER JOIN $SCHEMA.ORGANIZATION W_o ON W_o.ID = p.ORGANIZATION_ID
INNER JOIN (
	SELECT o2.ID, o2.LABEL, o2.QUERYABLE, o2.CREATED_AT, o2.UPDATED_AT,
	NULLIF(CONCAT_WS('|;|', ot.ID, ot.LABEL_TEXT_ID, ot.CREATED_AT, ot.UPDATED_AT),'') as ORGANIZATIONTYPE,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', t.ID, l.ID, l.CODE, l.LABEL, t.CONTENT),'') SEPARATOR '|^|'),'') as ORG_TYPE_LABEL
	FROM $SCHEMA.ORGANIZATION o2
	INNER JOIN $SCHEMA.ORGANIZATIONTYPE ot ON o2.ORGANIZATIONTYPE_ID = ot.ID
	INNER JOIN $SCHEMA.TEXT t ON t.ID = ot.LABEL_TEXT_ID
	INNER JOIN $SCHEMA.LANGUAGE l ON l.ID = t.LANGUAGE_ID
	GROUP BY o2.ID, o2.LABEL, o2.QUERYABLE, ORGANIZATIONTYPE, o2.CREATED_AT, o2.UPDATED_AT
) o ON o.ID = p.ORGANIZATION_ID
LEFT JOIN $SCHEMA.PROFILE_GROUP pg ON pg.PROFILE_ID = p.ID
LEFT JOIN $SCHEMA.`GROUP` W_g ON W_g.ID = pg.GROUP_ID
LEFT JOIN $SCHEMA.`GROUP` g ON g.ID = pg.GROUP_ID
LEFT JOIN $SCHEMA.PROFILE_PERMISSION pp ON pp.PROFILE_ID = p.ID
LEFT JOIN $SCHEMA.PERMISSION W_perm ON W_perm.ID = pp.PERMISSION_ID
LEFT JOIN (
	SELECT perm2.ID, perm2.`KEY`, perm2.EDITABLE, perm2.APPLICATION_ID, perm2.CREATED_AT, perm2.UPDATED_AT,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', t.ID, l.ID, l.CODE, l.LABEL, t.CONTENT),'') SEPARATOR '|^|'),'') as LABEL,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', td.ID, ld.ID, ld.CODE, ld.LABEL, td.CONTENT),'') SEPARATOR '|^|'),'') as DESCRIPTION
	FROM $SCHEMA.PERMISSION perm2
	INNER JOIN $SCHEMA.TEXT t ON t.ID = perm2.LABEL_TEXT_ID
	INNER JOIN $SCHEMA.LANGUAGE l ON l.ID = t.LANGUAGE_ID
	INNER JOIN $SCHEMA.TEXT td ON td.ID = perm2.DESCRIPTION_TEXT_ID
	INNER JOIN $SCHEMA.LANGUAGE ld ON ld.ID = td.LANGUAGE_ID
	GROUP BY perm2.ID, perm2.`KEY`, perm2.EDITABLE, perm2.APPLICATION_ID, perm2.CREATED_AT, perm2.UPDATED_AT
) perm ON perm.ID = pp.PERMISSION_ID
$WHERE_STATEMENT
GROUP BY p.ID, p.ALIAS, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT, USER, ORGANIZATION
$ORDER_BY_STATEMENT;