SELECT p.ID, p.ALIAS, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT,
NULLIF(CONCAT_WS('||', u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT),'') as `USER`,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', e.ID, e.ADDRESS, pe.IS_MAIN),'') SEPARATOR '|^|'),'') as EMAILS,
NULLIF(CONCAT_WS('||', o.ID, o.LABEL, o.QUERYABLE, o.CREATED_AT, o.UPDATED_AT, o.ORGANIZATIONTYPE, o.ORG_TYPE_LABEL),'') as ORGANIZATION,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', g.ID, g.NAME, g.CREATED_AT, g.UPDATED_AT),'') SEPARATOR '|^|'),'') as `GROUPS`,
NULLIF(GROUP_CONCAT(
	DISTINCT NULLIF(CONCAT_WS('||', perm.ID, perm.`KEY`, perm.EDITABLE, perm.APPLICATION_ID, perm.CREATED_AT, perm.UPDATED_AT, perm.LABEL, perm.DESCRIPTION),'')
	SEPARATOR '|^'),''
) as `PERMISSIONS`
FROM (
	SELECT ID, ALIAS, LASTNAME, FIRSTNAME, LAST_LOGIN, IS_ACTIVE, USER_ID, CREATED_AT, UPDATED_AT, ORGANIZATION_ID
	FROM FUSION.PROFILE $PAGINATION
) AS p
INNER JOIN FUSION.`USER` u ON u.ID = p.USER_ID
INNER JOIN FUSION.PROFILE_EMAIL pe ON pe.PROFILE_ID = p.ID
INNER JOIN FUSION.EMAIL e ON e.ID = pe.EMAIL_ID
INNER JOIN (
	SELECT o2.ID, o2.LABEL, o2.QUERYABLE, o2.CREATED_AT, o2.UPDATED_AT,
	NULLIF(CONCAT_WS('|;|', ot.ID, ot.LABEL_TEXT_ID, ot.CREATED_AT, ot.UPDATED_AT),'') as ORGANIZATIONTYPE,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', t.ID, l.ID, l.CODE, l.LABEL, t.CONTENT),'') SEPARATOR '|^|'),'') as ORG_TYPE_LABEL
	FROM FUSION.ORGANIZATION o2
	INNER JOIN FUSION.ORGANIZATIONTYPE ot ON o2.ORGANIZATIONTYPE_ID = ot.ID
	INNER JOIN FUSION.TEXT t ON t.ID = ot.LABEL_TEXT_ID
	INNER JOIN FUSION.LANGUAGE l ON l.ID = t.LANGUAGE_ID
	GROUP BY o2.ID, o2.LABEL, o2.QUERYABLE, ORGANIZATIONTYPE, o2.CREATED_AT, o2.UPDATED_AT
) o ON o.ID = p.ORGANIZATION_ID
LEFT JOIN FUSION.PROFILE_GROUP pg ON pg.PROFILE_ID = p.ID
LEFT JOIN FUSION.`GROUP` g ON g.ID = pg.GROUP_ID
LEFT JOIN FUSION.PROFILE_PERMISSION pp ON pp.PROFILE_ID = p.ID
LEFT JOIN (
	SELECT perm2.ID, perm2.`KEY`, perm2.EDITABLE, perm2.APPLICATION_ID, perm2.CREATED_AT, perm2.UPDATED_AT,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', t.ID, l.ID, l.CODE, l.LABEL, t.CONTENT),'') SEPARATOR '|^|'),'') as LABEL,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', td.ID, ld.ID, ld.CODE, ld.LABEL, td.CONTENT),'') SEPARATOR '|^|'),'') as DESCRIPTION
	FROM FUSION.PERMISSION perm2
	INNER JOIN FUSION.TEXT t ON t.ID = perm2.LABEL_TEXT_ID
	INNER JOIN FUSION.LANGUAGE l ON l.ID = t.LANGUAGE_ID
	INNER JOIN FUSION.TEXT td ON td.ID = perm2.DESCRIPTION_TEXT_ID
	INNER JOIN FUSION.LANGUAGE ld ON ld.ID = td.LANGUAGE_ID
	GROUP BY perm2.ID, perm2.`KEY`, perm2.EDITABLE, perm2.APPLICATION_ID, perm2.CREATED_AT, perm2.UPDATED_AT
) perm ON pp.PERMISSION_ID = perm.ID
$WHERE_STATEMENT
GROUP BY p.ID, p.ALIAS, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT, USER, ORGANIZATION;
