SELECT u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', p.ID, p.ALIAS, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT),'') SEPARATOR '|^|'),'') as PROFILES
FROM (
	SELECT ID, USERNAME, PASSWORD, CREATED_AT, UPDATED_AT
	FROM $SCHEMA.USER
	$PAGINATION
) AS u
INNER JOIN $SCHEMA.`PROFILE` W_p ON W_p.USER_ID = u.ID
INNER JOIN $SCHEMA.`PROFILE` p ON p.USER_ID = u.ID
$WHERE_STATEMENT
GROUP BY u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT
$ORDER_BY_STATEMENT;