SELECT u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('||', p.ID, p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.EMAILS, p.CREATED_AT, p.UPDATED_AT),'') SEPARATOR '|^|'),'') as PROFILES
FROM (
	SELECT ID, USERNAME, PASSWORD, CREATED_AT, UPDATED_AT
	FROM $SCHEMA.USER
	$PAGINATION
) AS u
INNER JOIN (
	SELECT p2.ID, p2.LASTNAME, p2.FIRSTNAME, p2.LAST_LOGIN, p2.IS_ACTIVE, p2.USER_ID, p2.CREATED_AT, p2.UPDATED_AT,
	NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|;|', e.ID, e.ADDRESS, pe.IS_MAIN),'') SEPARATOR '|^|'),'') as EMAILS
	FROM $SCHEMA.`PROFILE` p2
	INNER JOIN $SCHEMA.PROFILE_EMAIL pe ON pe.PROFILE_ID = p2.ID
	INNER JOIN $SCHEMA.EMAIL e ON e.ID = pe.EMAIL_ID
	GROUP BY p2.ID, p2.LASTNAME, p2.FIRSTNAME, p2.LAST_LOGIN, p2.IS_ACTIVE, p2.USER_ID, p2.CREATED_AT, p2.UPDATED_AT
) as p ON p.USER_ID = u.ID
$WHERE_STATEMENT
GROUP BY u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT
$ORDER_BY_STATEMENT;