SELECT u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT,
NULLIF(GROUP_CONCAT(DISTINCT NULLIF(CONCAT_WS('|>|', p.ID, ISNULL(p.ALIAS,'NULL'), p.LASTNAME, p.FIRSTNAME, p.LAST_LOGIN, p.IS_ACTIVE, p.CREATED_AT, p.UPDATED_AT),'') SEPARATOR '||'),'') as PROFILES
FROM (
	SELECT ID, USERNAME, PASSWORD, CREATED_AT, UPDATED_AT
	FROM $SCHEMA.USER
	$PAGINATION
) AS u
LEFT JOIN $SCHEMA.`PROFILE` W_p ON $INCLUDE_PROFILES AND W_p.USER_ID = u.ID
LEFT JOIN $SCHEMA.`PROFILE` p ON $INCLUDE_PROFILES AND p.USER_ID = u.ID
$WHERE_STATEMENT
GROUP BY u.ID, u.USERNAME, u.PASSWORD, u.CREATED_AT, u.UPDATED_AT
$ORDER_BY_STATEMENT;